sudo: false
language: go
go:
  - "1.10.3"
install:
  - mkdir -p bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.43/hugo_0.43_Linux-64bit.tar.gz -o bin/hugo.tar.gz
  - tar -xzvvf bin/hugo.tar.gz -C bin
before_script:
  - mkdir -p static/css
  - bin/hugo gen chromastyles --style github > static/css/syntax.css
script:
  - bin/hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  repo: koyokr/koyokr.github.io
  target-branch: master
  committer-from-gh: true
  on:
    branch: master
