baseURL = "https://koyo.kr/"
title = "KOYO.KR"
paginate = 5
theme = "beautifulhugo"

enableRobotsTXT = true
defaultContentLanguage = "ko"
languageCode = "ko"
hasCJKLanguage = true

pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

googleAnalytics = "G-F9925BGS1X"

[permalinks]
  post = "/post/:filename/"

[params]
  homeTitle = "KOYO.KR"
  subtitle = "컴퓨터할줄모름"
  logo = "img/avatar.jpg"
  favicon = "/favicon.png"
  commit = false
  rss = true
  comments = true
  readingTime = false
  hideAuthor = true
  useHLJS = false
  socialShare = false

  [params.giscus]
    repo = "koyokr/blog"
    repoId = "MDEwOlJlcG9zaXRvcnkxMzg4OTAzOTY="
    category = "Announcements"
    categoryId = "DIC_kwDOCEdMnM4B_3I_"
    mapping = "pathname"
    reactionsEnabled = true
    theme = "light"
    lang = "en"

[author]
  name = "koyo"
  website = "https://koyo.kr/"
  email = "koyo@koyo.kr"
  github = "koyokr"
  linkedin = "koyo"

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 2
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[sitemap]
  priority = 0.5
