baseURL = "https://koyo.kr/"
title = "KOYO KR"
paginate = 5
theme = "beautifulhugo"

enableRobotsTXT = true
defaultContentLanguage = "ko"
languageCode = "ko"
hasCJKLanguage = true

pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

disqusShortname = "koyo"
googleAnalytics = "UA-72551408-1"

[permalinks]
  post = "/post/:filename/"

[params]
  subtitle = "컴퓨터할줄모름"
  logo = "img/avatar.jpg"
  favicon = "/favicon.png"
  commit = false
  rss = true
  comments = true
  readingTime = false
  hideAuthor = true
  useHLJS = false
  socialShare = false

[author]
  website = "https://koyo.kr/"
  email = "koyo@koyo.kr"
  github = "koyokr"
  linkedin = "koyo"

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 2
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4
[sitemap]
  priority = 0.5
